spring:
  datasource:
    url: jdbc:mysql://dasarang.cnox2n905hyk.us-east-1.rds.amazonaws.com:3306/dasarang?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dasarang
    password: Dasarang12!!

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  cache:
    type: redis

  redis:
    host: redis
    port: 6379

jwt:
  refresh-exp: 2592000000
  access-exp: 3600000
  prefix: Bearer
  header: Authorization
  secret-key: difoi3iu2jioj132890u8979f7dxj1k2nbjkmhcxuasijf879687912yhjkhsdfuoiljkh13

app:
  apiUrl: https://open.neis.go.kr
  apiKey: 0c593213544f489d8762647e5722794b
  type: json
  pIndex: 1
  pSize: 10

api:
  key: exoid9n21oidx7duf3nfdsaf8dfi3ncdsa98f3hfcbusadf8i23jncds9fi23kjfmndsug89v0ik2m3ifndsf823kfjndsfydug898sdifk23mff39fds

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false

aws:
  access-key: AKIA2THTEVLROUSJCBMK
  secret-key: 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
  region: ap-northeast-2
  bucket: dasarang
  url: https://dasarang.s3.ap-northeast-2.amazonaws.com/

payment:
  toss:
    url: https://api.tosspayments.com
    secret-key: dGVzdF9za19CRTkyTEFhNVBWYlBrME9Ma3dwODdZbXBYeUpqOg==

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    tagsSorter: alpha
    operations-sorter: alpha
    display-request-duration: true

server:
  port: 8088
  forward-headers-strategy: framework
  error:
    whitelabel:
      enabled: false