spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  cache:
    type: redis

  redis:
    host: redis
    port: 6379

jwt:
  refresh-exp: ${JWT_REFRESH_EXP}
  access-exp: ${JWT_ACCESS_EXP}
  prefix: ${JWT_PREFIX}
  header: ${JWT_HEADER}
  secret-key: ${JWT_SECRET_KEY}

app:
  apiUrl: ${APP_API_URL}
  apiKey: ${APP_API_KEY}
  type: ${APP_TYPE}
  pIndex: ${APP_PINDEX}
  pSize: ${APP_PSIZE}

server:
  port: 8088
  forward-headers-strategy: framework
  error:
    whitelabel:
      enabled: false

